apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-resourcemanager
spec:
  package: xpkg.upbound.io/upbound/provider-azure-resourcemanager:v1.3.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-storage
spec:
  package: xpkg.upbound.io/upbound/provider-azure-storage:v1.3.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
