apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-compositions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FL40056213_wipro/Crossplane-Argo-Helm.git
    targetRevision: HEAD
    path: crossplane/compositions
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FL40056213_wipro/Crossplane-Argo-Helm.git
    targetRevision: HEAD
    path: crossplane/claims
  destination:
    server: https://kubernetes.default.svc
    namespace: azure-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
